### ISSUE TITLE
Problem when running CMD

### ISSUE THREAD

**Issue by cksakura** [medbioinf/pia#164]
Hello,

I encountered this problem when I use the CMD to run the PIA:

> 2021-03-22 23:13:47,855 ERROR PIAIntermediateJAXBHandler - Error while parsing PIA XML file
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 'f' (code 102) in prolog; expected '<'
 at [row,col {unknown-source}]: [1,1]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:653)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2133)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1181)
	at com.ctc.wstx.sr.BasicStreamReader.nextTag(BasicStreamReader.java:1204)
	at de.mpc.pia.intermediate.xmlhandler.PIAIntermediateJAXBHandler.parseXMLFile(PIAIntermediateJAXBHandler.java:188)
	at de.mpc.pia.intermediate.xmlhandler.PIAIntermediateJAXBHandler.parse(PIAIntermediateJAXBHandler.java:162)
	at de.mpc.pia.modeller.PIAModeller.parseIntermediate(PIAModeller.java:296)
	at de.mpc.pia.modeller.PIAModeller.loadFileName(PIAModeller.java:175)
	at de.mpc.pia.modeller.PIAModeller.<init>(PIAModeller.java:119)
	at de.mpc.pia.modeller.PIAModeller.processExecuteXMLFile(PIAModeller.java:799)
	at de.mpc.pia.modeller.PIAModeller.parseParameterXMLFile(PIAModeller.java:786)
	at de.mpc.pia.modeller.PIAModeller.main(PIAModeller.java:733)

I just generated the parameter file by the "-paramOutFile" command. 
Thanks for your help.

**Comment by julianu** [comment]
Apologies for the late reply, but could you elaborate, how you called PIA from the CLI?
Could you maybe also post the param file here, so I can double check it?

The generation of an "analysis pipeline file" via the command line is discouraged and, I am afraid, a bit out of date, if you tried this way. More effort went into the KNIME nodes lately and an update of the CLI is lacking behind.

**Comment by julianu** [comment]
You should use the json file to run a CLI analysis by now.
